// Mocks generated by Mockito 5.4.4 from annotations
// in ditonton/test/presentation_serial_tv/pages_serial_tv/serial_tv_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:ui' as _i13;

import 'package:ditonton/common/state_enum.dart' as _i9;
import 'package:ditonton/domain/entities_serial_tv/serial_tv.dart' as _i10;
import 'package:ditonton/domain/entities_serial_tv/serial_tv_detail.dart'
    as _i7;
import 'package:ditonton/domain/usercases_serial_tv/get_recommendations_serial_tv.dart'
    as _i3;
import 'package:ditonton/domain/usercases_serial_tv/get_serial_tv_detail.dart'
    as _i2;
import 'package:ditonton/domain/usercases_serial_tv/get_watchlist_status_serial_tv.dart'
    as _i4;
import 'package:ditonton/domain/usercases_serial_tv/remove_watchlist_serial_tv.dart'
    as _i6;
import 'package:ditonton/domain/usercases_serial_tv/save_watchlist_serial_tv.dart'
    as _i5;
import 'package:ditonton/presentation/provider_serial_tv/serial_tv_detail.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetSerialTvDetail_0 extends _i1.SmartFake
    implements _i2.GetSerialTvDetail {
  _FakeGetSerialTvDetail_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetSerialTvRecommendations_1 extends _i1.SmartFake
    implements _i3.GetSerialTvRecommendations {
  _FakeGetSerialTvRecommendations_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchListStatusSerialTv_2 extends _i1.SmartFake
    implements _i4.GetWatchListStatusSerialTv {
  _FakeGetWatchListStatusSerialTv_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveWatchlistSerialTv_3 extends _i1.SmartFake
    implements _i5.SaveWatchlistSerialTv {
  _FakeSaveWatchlistSerialTv_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveWatchlistSerialTv_4 extends _i1.SmartFake
    implements _i6.RemoveWatchlistSerialTv {
  _FakeRemoveWatchlistSerialTv_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSerialTvDetail_5 extends _i1.SmartFake
    implements _i7.SerialTvDetail {
  _FakeSerialTvDetail_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SerialTvDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockSerialTvDetailNotifier extends _i1.Mock
    implements _i8.SerialTvDetailNotifier {
  MockSerialTvDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetSerialTvDetail get getSerialTvDetail => (super.noSuchMethod(
        Invocation.getter(#getSerialTvDetail),
        returnValue: _FakeGetSerialTvDetail_0(
          this,
          Invocation.getter(#getSerialTvDetail),
        ),
      ) as _i2.GetSerialTvDetail);
  @override
  _i3.GetSerialTvRecommendations get getSerialTvRecommendations =>
      (super.noSuchMethod(
        Invocation.getter(#getSerialTvRecommendations),
        returnValue: _FakeGetSerialTvRecommendations_1(
          this,
          Invocation.getter(#getSerialTvRecommendations),
        ),
      ) as _i3.GetSerialTvRecommendations);
  @override
  _i4.GetWatchListStatusSerialTv get getWatchListStatusSerialTv =>
      (super.noSuchMethod(
        Invocation.getter(#getWatchListStatusSerialTv),
        returnValue: _FakeGetWatchListStatusSerialTv_2(
          this,
          Invocation.getter(#getWatchListStatusSerialTv),
        ),
      ) as _i4.GetWatchListStatusSerialTv);
  @override
  _i5.SaveWatchlistSerialTv get saveWatchlistSerialTv => (super.noSuchMethod(
        Invocation.getter(#saveWatchlistSerialTv),
        returnValue: _FakeSaveWatchlistSerialTv_3(
          this,
          Invocation.getter(#saveWatchlistSerialTv),
        ),
      ) as _i5.SaveWatchlistSerialTv);
  @override
  _i6.RemoveWatchlistSerialTv get removeWatchlistSerialTv =>
      (super.noSuchMethod(
        Invocation.getter(#removeWatchlistSerialTv),
        returnValue: _FakeRemoveWatchlistSerialTv_4(
          this,
          Invocation.getter(#removeWatchlistSerialTv),
        ),
      ) as _i6.RemoveWatchlistSerialTv);
  @override
  _i7.SerialTvDetail get serialTv => (super.noSuchMethod(
        Invocation.getter(#serialTv),
        returnValue: _FakeSerialTvDetail_5(
          this,
          Invocation.getter(#serialTv),
        ),
      ) as _i7.SerialTvDetail);
  @override
  _i9.RequestState get serialTvState => (super.noSuchMethod(
        Invocation.getter(#serialTvState),
        returnValue: _i9.RequestState.empty,
      ) as _i9.RequestState);
  @override
  List<_i10.SerialTv> get serialTvRecommendations => (super.noSuchMethod(
        Invocation.getter(#serialTvRecommendations),
        returnValue: <_i10.SerialTv>[],
      ) as List<_i10.SerialTv>);
  @override
  _i9.RequestState get recommendationState => (super.noSuchMethod(
        Invocation.getter(#recommendationState),
        returnValue: _i9.RequestState.empty,
      ) as _i9.RequestState);
  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);
  @override
  bool get isAddedToWatchlist => (super.noSuchMethod(
        Invocation.getter(#isAddedToWatchlist),
        returnValue: false,
      ) as bool);
  @override
  String get watchlistMessage => (super.noSuchMethod(
        Invocation.getter(#watchlistMessage),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#watchlistMessage),
        ),
      ) as String);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i12.Future<void> fetchSerialTvDetail(int? id) => (super.noSuchMethod(
        Invocation.method(
          #fetchSerialTvDetail,
          [id],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
  @override
  _i12.Future<void> addWatchlistSerialTv(_i7.SerialTvDetail? serialTvDetail) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWatchlistSerialTv,
          [serialTvDetail],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
  @override
  _i12.Future<void> removeFromWatchlistSerialTv(
          _i7.SerialTvDetail? serialTvDetail) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromWatchlistSerialTv,
          [serialTvDetail],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
  @override
  _i12.Future<void> loadWatchlistStatusSerialTv(int? id) => (super.noSuchMethod(
        Invocation.method(
          #loadWatchlistStatusSerialTv,
          [id],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
